### ISSUE TITLE
HeardingCATs DAO

### ISSUE THREAD

**Issue by Joshfairhead** [Giveth/gov-lab#7]
Check out the tweet from the Gitcoin people

**Comment by geleeroyale** [comment]
We talked about this during gov-lab 0.2 

Will try to herd cat herders to live demo at Aracon. Possibly need some quick whitelisting following that, but will do the onboarding myself.

**Comment by Joshfairhead** [comment]
Post for more context: https://medium.com/ethereum-cat-herders/decentralizing-ethereum-project-management-ffff4c09d0ea

**Comment by geleeroyale** [comment]
Discussed this with Lane Rettig at Aracon. The CH-DAO is fully funded for the coming year, so there is no immediate need for setting up a Giveth campaign for them. However, they are interested in using our DApp for their next funding run.

I am closing this for now, but hope the discussion will live up again a later point.

**Comment by Joshfairhead** [comment]
Cookies protocol?


ᐧ

**Comment by geleeroyale** [comment]
yes - I guess in GitHub terms this is the "Icebox" - I am making an exception here though, because this will stay inactive for such a long time - don't want to have it clog up the issue board.

**Comment by Joshfairhead** [comment]
Icebox is cookies, gotcha :)
---
Mobile: +44 (0) 7412090234
Calendar of my non-liquid commitments
<https://calendar.google.com/calendar/embed?src=joshafairhead%40gmail.com&ctz=Europe%2FLondon>
Calendar of my liquid arrangements
<https://calendar.google.com/calendar/embed?src=mef94j8i5evn7f89p76bsql89s%40group.calendar.google.com&ctz=Europe%2FLondon>
Loomio <https://www.loomio.org/g/Yx3rGU5I/techtonic>

ᐧ
